### ISSUE TITLE
why don't you do the register_buffer inside the QuantizedLinear() init ?

### ISSUE THREAD

**Issue by vince62s** [Cornell-RelaxML/quip-sharp#17]
instead of here: https://github.com/Cornell-RelaxML/quip-sharp/blob/main/model/llama_nofuse.py#L258-L260
and same for self attention
it would make things much easier to integrate the Class in other projects

**Comment by tsengalb99** [comment]
We actually did change this internally recently and are planning to merge it in after NeurIPS. I agree it would make it easier to integrate QuIP#.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Vincent Nguyen ***@***.***>
Sent: Wednesday, December 13, 2023 11:28:22 AM
To: Cornell-RelaxML/quip-sharp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/quip-sharp] why don't you do th register_buffer inside the QuantizedLinear() init ? (Issue #17)


instead of here: https://github.com/Cornell-RelaxML/quip-sharp/blob/main/model/llama_nofuse.py#L258-L260
and same for self attention
it would make things much easier to integrate the Class in other projects

**Comment by chu-tianxiang** [comment]
Curiously, why do we need to scale before quantization? I thought it may be related to the Q/K/V fuse, but unfused layers are also scaled first.

**Comment by tsengalb99** [comment]
It's just something we did, you can combine the scales in the unfused layers. The fused layers have a prescale to normalize the before they are scaled, but that's not strictly optimal. The unfused version of q/k/v gets like 0.02 better ppl on wikitext but is slower so we only released the fused versions.
