### ISSUE TITLE
can you provide example or code to compute hessians

### ISSUE THREAD

**Issue by waters222** [Cornell-RelaxML/quip-sharp#2]
does each model need different hessians for best performance?
for example if I want to using QuiP for DeepSeek models do I have to first to compute new hessians before quant?
or I can just re-use the llama2 hessians.

if I need to re-compute the hessians.
can you provide script or code example to do so?

**Comment by tsengalb99** [comment]
I updated the README to include instructions on generating Hessians. You will need to compute Hessians for DeepSeek before quantizing. Does DeepSeek use the Llama architecture (q/k/v/o/up/gate/down) or something else? If it uses the Llama architecture then the exisitng code should work. I didn't see a modeling_deepseek file in HF so if it uses modeling_llama then you shouldn't need to make any code changes - simply pass in the deepseek model card. If deepseek uses another architecture then things get a bit more complicated since we haven't implemented hessian_offline/quantize/hfize_<other architecture> yet. Doing so is pretty simple in that you just need to find the Linear layers in the architecture and modify the hessian_offline/quantize/hfize_llama files to reflect that.

**Comment by waters222** [comment]
thx!
