### ISSUE TITLE
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. Same issue as #4

### ISSUE THREAD

**Issue by luke-mcdermott-mi** [Cornell-RelaxML/quip-sharp#22]
Exact same issue as https://github.com/Cornell-RelaxML/quip-sharp/issues/4 , except setting batch size 1 does not work. Using same transformers==4.34.0 as well.

**Comment by tsengalb99** [comment]
What GPU are you using? Most likely you are running out of memory when trying to quantize a model.

**Comment by luke-mcdermott-mi** [comment]
A6000, so 48 gb

I am not quantizing, just trying to load 
`CUDA_VISIBLE_DEVICES=0 python gen_speed.py --hf_path relaxml/Mistral-7b-E8P-2Bit --batch_size 1`
I have tried with an without CUDA_VISIBLE_DEVICES=0
Adding the --no_use_cuda_graph makes it run, though this gets 2x as slow performance as standard mistral 7b

**Comment by tsengalb99** [comment]
This is expected. The base mistral model is incompatible with CUDA graphs which means that you can only run the quantized mistral models (mistral + openhermes) without CUDA graphs. The reason why it is twice as slow as fp16 without CUDA graphs is because we have more kernel launches in our code than a pure linear layer. CUDA graphs removes almost all the kernel launching overhead. From what I've heard, huggingface is actively trying to make its code more compatible with CUDA graphs, but you can always try to rewrite the incompatible parts on your own. 

The Llama 1 + 2 models work fine with CUDA graphs if you want to get a sense of speed with and without CUDA graphs.

**Comment by luke-mcdermott-mi** [comment]
I see, thank you for the clarification.
