### ISSUE TITLE
model size confirmation

### ISSUE THREAD

**Issue by ysong2123** [Cornell-RelaxML/quip-sharp#46]
Hi team,

i found https://huggingface.co/TheBloke/Llama-2-70B-Chat-AWQ,   this model declare using 4-bit quantization:
AWQ is an efficient, accurate and blazing-fast low-bit weight quantization method, currently supporting 4-bit quantization. Compared to GPTQ, it offers faster Transformers-based inference.

Meanwhile, https://huggingface.co/relaxml/Llama-2-70b-chat-E8P-2Bit/tree/main    this model used 2Bit quantization.

But the both model size are almost the same ~36.5GB.      Assumed Llama-2-70b-chat-E8P-2Bit will have more compact footprint size right?  could you help to confirm?

**Comment by tsengalb99** [comment]
If you look at the actual files, you’ll notice that huggingface screwed up and there are two copies of the model (safetensors out of 2 and safetensors out of 4). This is because HF uses git as a backend and the split size changed from 10GB to 5GB at some point, causing the naming to not match up anymore when uploading revisions. The safetensors out of 4 is the latest “correct” model. You can delete the out of 2 files.

 

From: ysong2123 ***@***.***> 
Sent: Monday, March 4, 2024 7:46 AM
To: Cornell-RelaxML/quip-sharp ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Cornell-RelaxML/quip-sharp] model size confirmation (Issue #46)

 

Hi team,

i found https://huggingface.co/TheBloke/Llama-2-70B-Chat-AWQ, this model declare using 4-bit quantization:
AWQ is an efficient, accurate and blazing-fast low-bit weight quantization method, currently supporting 4-bit quantization. Compared to GPTQ, it offers faster Transformers-based inference.

Meanwhile, https://huggingface.co/relaxml/Llama-2-70b-chat-E8P-2Bit/tree/main this model used 2Bit quantization.

But the both model size are almost the same ~36.5GB. Assumed Llama-2-70b-chat-E8P-2Bit will have more compact footprint size right? could you help to confirm?

**Comment by ysong2123** [comment]
@tsengalb99 you mean delete:
[model-00001-of-00002.safetensors] and [model-00002-of-00002.safetensors]  right?

**Comment by tsengalb99** [comment]
Yes, correct
