### ISSUE TITLE
had_left_T and had_right 

### ISSUE THREAD

**Issue by dorsa-zeinali** [Cornell-RelaxML/quip-sharp#78]
Hi, 
Are the had_left_T and had_right attributes in the quantized_linear class the hadamard matrices used in algorithm 2 (quip-inference)? 
thank you!

**Comment by dorsa-zeinali** [comment]
also, the su and sv vectors are being fine-tuned both as quantization is happening and one time at the end ?

**Comment by dorsa-zeinali** [comment]
also, why is the returned hadK None when n is a power of 2? does that get changed later on ?

**Comment by tsengalb99** [comment]
The had_left and had_right matrices are the "small Hadamard matrices" described in the paper. hadK is None when n is a power of 2 because Hadamard matrices are fully recursively defined for powers of 2 (ie the small matrix is just [1]).

The SU/SV vectors are fine-tuned after quantization. I would also recommend reading the [QTIP code](https://github.com/Cornell-RelaxML/qtip) if you want a better understanding of what's going on. The QuIP# code has some extra stuff that is not part of the algorithm.

**Comment by dorsa-zeinali** [comment]
Is there somewhere where the hadK is changed to something else when it is none? I don't really see that in the codebase. 
and okay, I will look at the qtip code. thanks.

**Comment by dorsa-zeinali** [comment]
when you mean the small matrix is just 1, would it just be multiplying by 1?

**Comment by tsengalb99** [comment]
This is where hadK is used https://github.com/Cornell-RelaxML/quip-sharp/blob/1d8f873e9a2a8b86b12bb1064c312c5689b77d98/lib/utils/matmul_had.py#L101. hadK is the small Hadamard matrix for the recursive definition. If K = 1 (n is a power of 2), then hadK is just `[1]`, which means that we can skip multiplying by it.
